#
# version.cmake : version du projet
#

set (SMOOTH3D_MAJOR_VERSION "3")
set (SMOOTH3D_MINOR_VERSION "3")
set (SMOOTH3D_RELEASE_VERSION "2")
set (SMOOTH3D_VERSION ${SMOOTH3D_MAJOR_VERSION}.${SMOOTH3D_MINOR_VERSION}.${SMOOTH3D_RELEASE_VERSION})


